<?php

/* This is global array of translation strings used for internal theme translation */

global $vlog_translate;

$vlog_translate = array(
	'no_videos_message' => array( 'text' => esc_html__( 'No videos yet!', 'vlog' ), 'desc' => 'No videos yet!' ),
	'watch_later_message' => array( 'text' => esc_html__( 'Click on "Watch later" to put videos here', 'vlog' ), 'desc' => 'Click on "Watch later" to put videos here' ),
	'views' => array( 'text' => esc_html__( 'views', 'vlog' ), 'desc' => 'Used in post meta data (number of views)' ),
	'vid_duration' => array( 'text' => esc_html__( 'min', 'vlog' ), 'desc' => 'Used in post meta data (reading time)' ),
	'watch_later' => array( 'text' => esc_html__( 'Watch Later', 'vlog' ), 'desc' => 'Watch later action label' ),
	'watch_later_remove' => array( 'text' => esc_html__( 'Remove', 'vlog' ), 'desc' => 'Remove from watch later action label' ),
	'cinema_mode' => array( 'text' => esc_html__( 'Cinema Mode', 'vlog' ), 'desc' => 'Cinema mode action label' ),
	'read_more' => array( 'text' => esc_html__( 'Read More', 'vlog' ), 'desc' => 'Label for read more link' ),
	'category' => array('text' => esc_html__('', 'vlog'), 'desc' => 'Category title prefix'),
	'tag' => array('text' => esc_html__('#', 'vlog'), 'desc' => 'Tag title prefix'),
	'search_placeholder' => array('text' => esc_html__('Type here to search...', 'vlog'), 'desc' => 'Search placeholder text'),
	'search_results_for' => array('text' => esc_html__('Search results for', 'vlog'), 'desc' => 'Title for search results template'),
	'newer_entries' => array('text' => esc_html__('Newer items', 'vlog'), 'desc' => 'Pagination (prev/next) link text'),
	'older_entries' => array('text' => esc_html__('Older items', 'vlog'), 'desc' => 'Pagination (prev/next) link text'),
	'previous_posts' => array('text' => esc_html__('Previous', 'vlog'), 'desc' => 'Pagination (numeric) link text'),
	'next_posts' => array('text' => esc_html__('Next', 'vlog'), 'desc' => 'Pagination (numeric) link text'),
	'load_more' => array('text' => esc_html__('Load More', 'vlog'), 'desc' => 'Pagination (load more) link text'),
	'related' => array('text' => esc_html__('You may also like', 'vlog'), 'desc' => 'Related posts area title'),
	'related_cover_title' => array('text' => esc_html__('Related videos', 'vlog'), 'desc' => 'Related videos label in cover area'),
	'video_sticky_title' => array('text' => esc_html__('Currently playing', 'vlog'), 'desc' => 'Title in sticky video box'),
	'view_all' => array('text' => esc_html__('View all posts', 'vlog'), 'desc' => 'View all posts link text in author box'),
	'share_facebook' => array('text' => esc_html__('Facebook', 'vlog'), 'desc' => 'Facebook button label'),
	'share_twitter' => array('text' => esc_html__('Twitter', 'vlog'), 'desc' => 'Twitter button label'),
	'share_reddit' => array('text' => esc_html__('Reddit', 'vlog'), 'desc' => 'Reddit button label'),
	'share_gplus' => array('text' => esc_html__('Google+', 'vlog'), 'desc' => 'Google+ button label'),
	'share_pinterest' => array('text' => esc_html__('Pinterest', 'vlog'), 'desc' => 'Pinterest button label'),
	'share_email' => array('text' => esc_html__('Email', 'vlog'), 'desc' => 'Email button label'),
	'share_stumbleupon' => array('text' => esc_html__('StumbleUpon', 'vlog'), 'desc' => 'StumbleUpon button label'),
	'share_linkedin' => array('text' => esc_html__('LinkedIN', 'vlog'), 'desc' => 'LinkedIN button label'),
	'share_whatsapp' => array('text' => esc_html__('WhatsApp', 'vlog'), 'desc' => 'WhatsApp button label'),
	'share_vKontakte' => array('text' => esc_html__('vKontakte', 'vlog'), 'desc' => 'vKontakte button label'),
	'prev_post' => array('text' => esc_html__('Previous', 'vlog'), 'desc' => 'Previous post label'),
	'next_post' => array('text' => esc_html__('Next', 'vlog'), 'desc' => 'Next post label'),
	'page_of' => array('text' => esc_html__('Page %s of %s', 'vlog'), 'desc' => 'Paginated/multi-page post navigation label'),
	'404_title' => array('text' => esc_html__('404 error: Page not found', 'vlog'), 'desc' => '404 page title'),
	'404_text' => array('text' => esc_html__('The page that you are looking for does not exist on this website. You may have accidentally mistype the page address, or followed an expired link. Anyway, we will help you get back on track. Why not try to search for the page you were looking for:', 'vlog'), 'desc' => '404 page text'),
	'content_none' => array('text' => esc_html__('Sorry, there are no posts found on this page. Feel free to contact website administrator regarding this issue.', 'vlog'), 'desc' => 'Message when there are no posts on archive pages. i.e Empty Category'),
	'content_none_search' => array('text' => esc_html__('No results found. Please try again with a different keyword.', 'vlog'), 'desc' => 'Message when there are no search results.'),
	'responsive_more' => array('text' => esc_html__('More', 'vlog'), 'desc' => 'Secondary navigation link label on responsive/mobile menu.'),
	'username_email_label' => array('text' => esc_html__('Username or Email Address', 'vlog'), 'desc' => 'Label for "username and email address" in header login form'),
	'password_label' => array('text' => esc_html__('Password', 'vlog'), 'desc' => 'Label for password in header login form'),
	'remember_me' => array('text' => esc_html__('Remember Me', 'vlog'), 'desc' => 'Label for remember me checkbox in header login form'),
	'log_in' => array('text' => esc_html__('Login', 'vlog'), 'desc' => 'Label for login button in header login form'),
	'log_out' => array('text' => esc_html__('Logout', 'vlog'), 'desc' => 'Label for logout button in header login form'),
	'registration_link' => array('text' => esc_html__('Register', 'vlog'), 'desc' => 'Label for register link in header login form'),
	'lost_password' => array('text' => esc_html__('Lost Password?', 'vlog'), 'desc' => 'Label for lost password link in header login form'),
	'wifi_subcription_form_title_only' => array('text' => esc_html__('Only', 'vlog'), 'desc' => 'Title (part 1) in Wifi Subscription form'),
	'wifi_subcription_form_title_weekly' => array('text' => esc_html__('per week for unlimited Videos', 'vlog'), 'desc' => 'Title (part 2) in Wifi Subscription form'),
	'wifi_subcription_badge' => array('text' => esc_html__('Subscription', 'vlog'), 'desc' => 'Badge in Wifi Subscription form'),
	'subscribe_text' => array('text' => esc_html__('Subscribe for unlimited videos', 'vlog'), 'desc' => 'Label for Subscribe text in wifi page '),
	'phone_number' => array('text' => esc_html__('Type your phone number:', 'vlog'), 'desc' => 'Label for phone number in wifi page '),
	'select_carrier' => array('text' => esc_html__('Select your carrier:', 'vlog'), 'desc' => 'Select carrier in Wifi page'),
	'already_have_account' => array('text' => esc_html__('I already have an account', 'vlog'), 'desc' => 'Label for Wifi page'),
	'continue' => array('text' => esc_html__('Continue', 'vlog'), 'desc' => 'Label for continue text '),
	'cancel' => array('text' => esc_html__('Cancel', 'vlog'), 'desc' => 'Label for cancel text '),
	'cancel_confirmation' => array('text' => esc_html__('Are you sure you want to cancel your subscription?', 'vlog'), 'desc' => 'Label for cancel confirmation text after user clicked on cancel button'),
	'noaccesspage_disclaimer' => array('text' => esc_html__('Dear user. Unfortunately this service is only available in the 3G network. Please turn off your wifi connection in your device in Settings-> Wifi and visit us again. Thank you for understanding.', 'vlog'), 'desc' => 'Label for no access page disclaimer text '),
);

?>
